### ISSUE TITLE
Twitch Chat Channel Name Issue

### ISSUE THREAD

**Issue by ahmeema19** [Alphalaneous/Twitch-Chat#1]
my twitch channel has an underscore in it, and that's a character you're not able to type in geometry dash. Is there a mod or some other method that allows a bypass of the special characters or would i have to change my username entirely for it to work?

Thank you.

**Comment by Alphalaneous** [comment]
Currently there is a geode bug where the text filter set for the input just doesn’t work. Unfortunately I cannot fix that on my end and you’ll have to use a hack for it. If you have megahack for example, the text length bypass also bypasses the character filter.

**Comment by Alphalaneous** [comment]
I will likely add another way to set the name in the meantime in a future update.

**Comment by ahmeema19** [comment]
Thank you, I appreciate it.

**Comment by Alphalaneous** [comment]
I would like to keep this open such that I remember to implement the needed change

**Comment by Alphalaneous** [comment]
Hacky fix added for the time being until geode updates
